### ISSUE TITLE
Resource Not Found Exception only in Marshmallow 6.0.1

### ISSUE THREAD

**Issue by nicemak** [android/app-bundle-samples#36] opened 2019-12-03 06:00 UTC
Hi,

I followed dynamic delivery sample https://codelabs.developers.google.com/codelabs/on-demand-dynamic-delivery/index.html#0.

i uploaded to internal test and after i installed it successfully launch the app, download the dynamic module, after dynamic module is downloaded when i click to open it crash says Resource Not Found exception, then i just modify the version code and re uploaded the aab file without changing anything in functionality. and updated the app and it works! i dont know what causes for the first time when module downloaded successfully. it happened only in Marshmallow 6.0.1 custom rom, i use custom rom because i have to use dynamic delivery feature in my app. can someone please help me out.

Same app is working fine on Pie on first time.

**Comment by nicemak** [comment] 2019-12-07 10:59
You can check details here: https://stackoverflow.com/questions/59151392/android-dynamic-delivery-resource-not-found-exception-on-marshmallow-6-0-1

i already mentioned the exact steps, but this crash problem is only happens in Marshmallow 6.0.1 its working fine in 7.0 7.1.1 8 9 and 9.1.1

**Comment by keyboardsurfer** [comment] 2019-12-13 10:37
I'm assuming that your main problem comes from the custom ROM you're running as I can not reproduce the issue here. The [answer given by Pierre](https://stackoverflow.com/a/59151833/422060) is your best shot for the device.
Other than that I recommend using an emulator with PlayStore enabled.

**Comment by coreform** [comment] 2020-01-07 06:52
I've been seeing this problem in the wild on Android 6.0.1 and 5.1 and only for a particular resource in multiple layouts within the app. Google's documentation indicates that language splitting is only available for Android Instant App Projects, that doesn't apply to my project, while the documentation also indicates that screen density splitting is disabled by default. So I wonder whether there is anything I can do, or whether the documentation is misleading?

**Comment by keyboardsurfer** [comment] 2020-01-07 10:14
AFAICT langauge splits are no longer restricted to Instant Apps.
Can you link me to the documentation that made these claims so I can make sure they get corrected?

**Comment by coreform** [comment] 2020-01-07 10:16
https://developer.android.com/studio/build/configure-apk-splits

**Comment by keyboardsurfer** [comment] 2020-01-07 10:29
When using the `com.android.dynamic-feature` plugin or creating `.aab` files you don't need to build multi-apk any more. So instead of doing multi-apk just create a bundle using `./gradlew bundle` and you're good to go without gradle configuration.

**Comment by amitgroch** [comment] 2020-07-06 05:44
I am also facing same issue one First time I am getting this issue after that its working fine.

**Comment by amitgroch** [comment] 2020-07-06 05:47
I am also facing the same issue after download the Dymaic module only first time my app is crash after that it work fine.

android.content.res.Resources$NotFoundException: Resource ID #0x7e090004
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7e090004
        at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:239)
        at android.content.res.MiuiResourcesImpl.getValue(MiuiResourcesImpl.java:96)
        at android.content.res.Resources.loadXmlResourceParser(Resources.java:2309)
        at android.content.res.Resources.getLayout(Resources.java:1189)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.h.c(AppCompatDelegateImpl.java:695)
        at androidx.appcompat.app.e.setContentView(AppCompatActivity.java:170)
        at com.kdanmobile.demo.screenui.reader.view.activity.PDFBaseActivity.onCreate(PDFBaseActivity.java:146)

**Comment by keyboardsurfer** [comment] 2020-07-06 08:48
Thanks for checking in here, @amitgroch.
Can you reproduce the issue through the sample at hand?
Also, what kind of device / OS configuration do you use when running into this issue?

**Comment by keyboardsurfer** [comment] 2020-08-10 16:05
We need your input to act on this issue.
This issue will be closed soon unless there is further actionable input.

**Comment by yeuristic** [comment] 2020-08-13 10:41
Hi @keyboardsurfer We are also facing the same issue. We have many crash logs in our Firebase Crashlytics related to this.
I also can reproduce the issue, I've created the simple project for you to take a look.
https://github.com/yeuristic/dynamic-feature-marshmallow-crash

PS: based on our Crashlytics logs, this issue exists only in device with OS 5.0 or 6.0. So, to reproduce the issue you should use emulator or device with OS version 5.0 or 6.0
I can reproduce the crash with device with OS 6.0, but it's fine if I run this project with Oreo OS.
Thanks.

**Comment by keyboardsurfer** [comment] 2020-08-13 11:08
Thanks for creating this. How do you invoke the build script? `./install` and `./install bundleDebug` both fail on my end.

**Comment by yeuristic** [comment] 2020-08-13 14:26
please try ./install app:bundleDebug.
Because my script needs `app` information to locate the generated .aab file.
Thank you

**Comment by manisoft83** [comment] 2020-08-19 12:18
I am also facing the same issue for couple of Marshmallow users, however I provide Universal APK for those who is facing this issue.
Currently, I don't have fix to provide but have work around.

**Comment by yeuristic** [comment] 2020-08-19 22:21
Hi @manisoft83, thanks for sharing. I wonder what do you mean by providing universal APK for those who are impacted by this issue. Are you manually send them your universal APK so they can install it manually and not using Play Store, Or how?
Thanks in advance

**Comment by keyboardsurfer** [comment] 2020-09-14 11:12
Without seeing dependencies it's tricky to pinpoint this down.
We have seen issues similar to this one that were fixed by moving to ConstraintLayout (CL) 2.0.0 or newer.
Can you confirm that you're using an older version of CL and that the issue is resolved by upgrading the version?

**Comment by yeuristic** [comment] 2020-09-15 08:11
Thank you @keyboardsurfer.
Yes we can confirm after updating ConstraintLayout to 2.0.1, the problem is fixed.
Fyi, this [problem](https://stackoverflow.com/questions/53625467/constraintlayout-barrier-in-dynamic-feature-module-fails) can also be solved by updating ConstraintLayout library.

**Comment by iamkdblue** [comment] 2020-12-23 07:28
@keyboardsurfer Thanks for this library!
I am getting  this error `android.content.res.Resources$NotFoundException: Resource ID #0x7e070002` in android 6.0.1 .

As you said use ConstraintLayout (CL) 2.0.0 or newer. i am currently using `androidx.constraintlayout:constraintlayout:2.0.3`

**Comment by keyboardsurfer** [comment] 2021-01-05 17:15
@iamkdblue That's not expected. Can you create a PR against the sample where you reproduce this issue?

**Comment by iamkdblue** [comment] 2021-01-06 18:30
@keyboardsurfer I am using a feature module in our app, it's only crashing in android 5 and android 6 and I raise this issue at google [issuetracker](https://issuetracker.google.com/u/1/issues/176416918).

**Comment by keyboardsurfer** [comment] 2021-01-07 17:22
Do you have fusing of modules enabled as [described in the documentation](https://developer.android.com/guide/app-bundle#multi_apks)?

**Comment by iamkdblue** [comment] 2021-01-08 05:20
@keyboardsurfer we are targeting API 21 and above that. The above link is for Devices running Android 4.4 (API level 19) and lower.

**Comment by keyboardsurfer** [comment] 2021-01-08 11:40
Moving the discussion to Google issuetracker as this issue is unrelated to the sample at hand.

**Closed by keyboardsurfer** 2021-01-08 11:40 UTC
