### ISSUE TITLE
Error code -2 when creating a new module for a shipped application

### ISSUE THREAD

**Issue by Javinator9889** [android/app-bundle-samples#53] opened 2020-04-23 09:56 UTC
I have created an application (source available here: https://gitlab.javinator9889.com/Javinator9889/handwashing-reminder) and at first deployment I created only two modules and the base one:

- `appintro` module
- `ads` module
- Base application

After some time I decided to create two new modules for specific devices:

- `okhttp` module (Android 5.0 and higher)
- `okhttplegacy` module (for Android 4.4 or lower)

The point is that if I try to update an already installed application the new module is `MODULE_UNAVAILABLE` (error code `-2` - see [Android Developers](https://developer.android.com/reference/com/google/android/play/core/splitinstall/model/SplitInstallErrorCode#module_unavailable). The only solution I found is to **completely remove the installed app** and install it again. At this point, the module installs successfully.

Is there anyway to avoid this behaviour? The actual branch I am working on is `development` ([development branch](https://gitlab.javinator9889.com/Javinator9889/handwashing-reminder/-/tree/development)).

Any help is welcomed :smile:

**Comment by keyboardsurfer** [comment] 2020-05-05 14:51
Hi @Javinator9889. This is not an issue with the sample at hand and not an issue that usually occurs. Adding a dynamic feature module during development, then upgrading the app on device, and downloading the new module is supported behavior.  

Best ask a question on StackOverflow, as this is would require a review of your code.  
I did take a look at your development branch, but couldn't find the new modules.

**Comment by Javinator9889** [comment] 2020-05-05 14:58
Hi @keyboardsurfer 

Thank you so much for answering me. As I didn't get the modules working during development, I removed them from branch. They are still available here: https://gitlab.javinator9889.com/Javinator9889/handwashing-reminder/-/tree/a4a5f410971f9f5fc836cf6bd6d1604a547cdaeb
At that point, the modules [`OkHttp` and `OkHttpLegacy`] were working on fresh install but as I said I could not make them work when upgrading the app.
Maybe the issue is related to the [`DynamicFeatureProgress`](https://gitlab.javinator9889.com/Javinator9889/handwashing-reminder/-/blob/a4a5f410971f9f5fc836cf6bd6d1604a547cdaeb/app/src/main/java/com/javinator9889/handwashingreminder/activities/DynamicFeatureProgress.kt) activity which downloads and installs the modules.

I thought the error was not expected to happen and usually it should download the new modules correctly. I will review my code for any kind of error that may exist, but would you mind if I ask you to also have a look at it? I think I did everything ok.

Thank you so much in advance.

P.D.: I did question in StackOverflow time ago but I didn't have any response: https://stackoverflow.com/questions/61384372/error-code-2-when-creating-a-new-module-for-a-shipped-application

**Comment by keyboardsurfer** [comment] 2020-05-05 15:14
> At that point, the modules [OkHttp and OkHttpLegacy] were working on fresh install but as I said I could not make them work when upgrading the app.
This doesn't sound right. How did you test the upgrade flow?

**Comment by Javinator9889** [comment] 2020-05-05 16:09
@keyboardsurfer the workflow consisted on releasing the new update and view that all the installations had the same error (-2) that said that the module was unavailable

On my own, I developed a test version not having the modules and installed on a test device
Then, I included a new module and updated the app (all this steps done using the Internal app sharing) and I saw that I got the error -2 and the module didn't install. For more testing, I did a new update on the test device for seeing if maybe after two updates the module is available but it wasn't.

Finally, I uninstalled the application and installed both the new versions I did for testing (installed one and uninstalled before installing the following) and in both cases the modules downloaded and installed completely

**Comment by keyboardsurfer** [comment] 2020-05-06 15:46
You can test this yourself in a more closely tied loop [as described in this article](https://medium.com/androiddevelopers/developer-tools-on-play-store-85fb710ee33b#fc43).  
Like I said above, this is not intended behavior. Adding a dynamic feature module and removing it should not cause any issues after the version on device has been upgraded.

**Comment by Javinator9889** [comment] 2020-05-06 15:51
@keyboardsurfer I will have a look
Thank you so much for your help :smile:

**Comment by keyboardsurfer** [comment] 2020-05-15 11:06
Thanks. Closing this issue for now. Please come back to it if there are things we can investigate further.

**Closed by keyboardsurfer** 2020-05-15 11:06 UTC
